### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/proc'

### ISSUE THREAD

**Issue by wtrought** [xolox/python-rsync-system-backup#1]
Upon installation, the command line interface does not work due to '/proc' missing. I have the proc directory as well. 

The error resides in
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/proc/core.py", line 693, in find_processes

Should note that this installation was done by pip install

**Comment by xolox** [comment]
Hi Winston and thanks for the feedback. The first line of the readme mentions:

> The rsync-system-backup program uses rsync to create **full system backups of Linux systems**.

Judging by the filename (`/Library/Frameworks/Python.framework/...`) in the error message you are running macOS. This is not a supported platform.

In an attempt to more explicitly signal unsupported platforms I've now added an error message that needs to be bypassed using the `-f` or `--force` option.

This doesn't change macOS support for you, but hopefully it avoids confusion for other users.
